### ISSUE TITLE
Review classes used in localgov_media CKEditor styles config

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_core#110]
The localgov_media [editor.editor.wysiwyg.yml](https://github.com/localgovdrupal/localgov_core/blob/2.x/modules/localgov_media/config/optional/editor.editor.wysiwyg.yml) includes a small set of WYSIWYG custom styles for Highlight, External link, etc, which are using legacy and Bootstrap classes.

These may need supplementing with additional classes to maintain consistency in localgov_base.

**Comment by markconroy** [comment]
@danchamp I've tackled this in https://github.com/localgovdrupal/localgov_base/commit/954299d2a223a21a230d89949d44d2aa08bdc5bb

**Comment by danchamp** [comment]
@markconroy Nice, happy to close this.
