### ISSUE TITLE
Module updates for new roles

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_core#115]
Hello,
I can see that two new roles called "Contributor" and "User manager" have been added [recently](https://github.com/localgovdrupal/localgov_core/commit/c5ec12f69869ea8fb29c9c99e287060f8b685a97).  But I can't see any update hook implementation to actually import the relevant config files ([example](https://github.com/localgovdrupal/localgov_core/blob/2.x/modules/localgov_roles/config/install/user.role.localgov_contributor.yml)).  Does it mean these roles are optional?

**Comment by stephen-cox** [comment]
@Adnan-cds Apologies for the delay in getting back to you. There was the idea that people already using the Roles modules will likely have customised these and so we don't necessarily want to impose these on everyone.

That said, I think the Contributor role is assumed to exist if you're using the Workflows module and I may have overlooked ensuring this role exists when enabling Workflows, which may causes issues. So we'll likely need to add a update / install hook to Workflows for this.

Are you using the Roles module in Croydon and would you want the extra roles that have been added? An alternative to writing an update hook to enforce the new roles would be to use [Config Sync](https://www.drupal.org/project/config_sync) to selectively apply upstream config changes; something that's been discussed but not implemented yet.

**Comment by Adnan-cds** [comment]
> so we don't necessarily want to impose these on everyone.

Got it.  Thanks.

> So we'll likely need to add a update / install hook to Workflows for this.

+1

> Are you using the Roles module in Croydon

Yes, we are.

> and would you want the extra roles that have been added?

I have directly imported the config files, so should be okay for now.  I was just worried about unsuspecting site builders missing out on these new goodies.

**Comment by stephen-cox** [comment]
I have created an issue for the missing contributor role when workflows is enabled: https://github.com/localgovdrupal/localgov_workflows/issues/5

There are ongoing discussions about the best way to communicate updates and changes to LocalGov Drupal.
