### ISSUE TITLE
Editor role should have the bypass access control permisson

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_core#125]
Assuming editor role is essentially meant to be the 'god mode' in terms of content editing, would it make sense to give the localgov_editor role the `bypass node access` (Bypass content access control).

Spotted as some of our custom content types where not editable by default, and whilst I can add a function to assign correct permisisons, would it not make sense to add this by default?

**Comment by keelanfh** [comment]
I wouldn't be in favour of this change - at some point, we ended up with `bypass node access` enabled and it made it a bit difficult to figure out why removing content editing permissions for certain content types was having no effect.

**Comment by andybroomfield** [comment]
Did we decide against this change? If so this can close but would be good to get confirmation.
BHCC did implement this, but thats becuase our editors need to be able to edit all site content, sounds like that wouldn't work for everyone.

**Comment by andybroomfield** [comment]
Turns out this is a problem as it stops node_access control modules working and can cause deletion of content that shouldn't be!
