### ISSUE TITLE
Custom patch failed for drupal/field_group:3.3.0

### ISSUE THREAD

**Issue by tran-bigbluedoor** [localgovdrupal/localgov_core#147]
Error: Cannot apply the patch `"Fix 'Undefined property: stdClass::$region' error #3059614": "https://www.drupal.org/files/issues/2020-06-15/3059614-37.patch"` when execute `composer update`:

<img width="1098" alt="Screenshot 2022-09-20 at 11 05 44" src="https://user-images.githubusercontent.com/102959744/191230173-8806df0f-eb74-4120-ba0d-75b94609f637.png">

Explanation: New version (3.3.0) of `field_group` module has fixed this issue: https://www.drupal.org/project/field_group/releases/8.x-3.3

Suggestion: Remove the `field_group` patch from `composer.json` file:

<img width="1042" alt="Screenshot 2022-09-20 at 11 07 55" src="https://user-images.githubusercontent.com/102959744/191230666-bf9cee64-f380-43f9-a107-4dca48f8b468.png">

**Comment by finnlewis** [comment]
Thanks @tran-bigbluedoor!

Any chance you could create a pull request for review?  

Then @ekes @stephen-cox @Adnan-cds or @andybroomfield or I might be able to review?

**Comment by tran-bigbluedoor** [comment]
Hi @finnlewis , I have created a PR here: https://github.com/localgovdrupal/localgov_core/pull/148

**Comment by finnlewis** [comment]
Thanks @tran-bigbluedoor - @ekes is just double checking and we'll get it merged and hopefully do a release.

**Comment by finnlewis** [comment]
Released https://github.com/localgovdrupal/localgov_core/releases/tag/2.1.7

Thanks @tran-bigbluedoor and @ekes !
