### ISSUE TITLE
media_library_edit missing schema - the module does not define schema, so tests are failing.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_core#153]
Since we introduce [media_library_edit](https://www.drupal.org/project/media_library_edit) to allow content managers to edit images and other media, many tests are failing due to missing schema. 

Failing tests like: 

`core.entity_form_display.paragraph.localgov_image.default:content.localgov_image.third_party_settings.media_library_edit missing schema`

See: https://github.com/localgovdrupal/localgov_project/actions/runs/3335286356/jobs/5519111640#step:5:23

I've created an issue on drupal.org to try to get it fixed, no joy yet, so cross posting here: https://www.drupal.org/project/media_library_edit/issues/3315757

**Comment by andybroomfield** [comment]
This is fixed, but we need localgov_core to update to media_library_edit 3.0.1

**Comment by finnlewis** [comment]
Good point @andybroomfield ! I'll start a branch.
