### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_core#158]
Issue to track any changes needed to support Drupal 10

**Comment by stephen-cox** [comment]
Adding non-existent permissions to a role is not allowed. The incorrect permissions are "use text format wysiwyg". 

Caused by https://github.com/localgovdrupal/localgov_core/blob/f857b3e566e4687087bffd7e277fc4a594cefb04/modules/localgov_media/localgov_media.module#L17

I think this is because the relevant config is in optional and so not guaranteed to be installed.

**Comment by stephen-cox** [comment]
@ekes @finnlewis @Adnan-cds @andybroomfield  Having the localgov_media config in `optional` has caused us all sort of issues when trying to use LGD module in other places (Microsites being a prime example). I seem to remember this was done so we don't cause problems when trying to use LGD modules with existing sites. But this is no longer an issue and pretty much everyone is going to be installing LGD with the profile.

Can you think of any reasons we shouldn't move the config in the ;ocalgov_media module into `install` to make it required? If not, I propose doing this as part of the Drupal 10 upgrade work along with a minor / major release of localgov_core.

**Comment by andybroomfield** [comment]
What would be the issue with the config being in optional?
I thought that the config would still be installed if the config is in optional, providing the dependencies are present.

Looking at the config, it is the image styles and media entities that get installed, which one would expect anyway, so that moves it in favour of putting in install.

The counter is that some councils (ahem BHCC) are looking at removing many of the image formats included and replacing with our own as we have different image styles that we are planning to use, though it does take looking through where certian images and media displays are dependant on them.

So I guess we need to decide if we expect (on at least first install) that modules will have the media and image styles avalible, and then pick up issues to make them configurable for those that need to change them.

**Comment by andybroomfield** [comment]
By @ekes in #129

> The localgov_media is all in optional so I think it gets evaluated later. If there is a module depending on these (localgov_homepage_paragraphs, localgov_subsites) depending on how they are installed it can fail

and

> See #130 for a blow-by-blow discovery of why they are in optional, and probably should stay there, and what we should do or not do in the future.

**Comment by stephen-cox** [comment]
Thanks @andybroomfield I knew there should be some discussion about having media config in optional somewhere.

The issue this causes is there are hooks in some modules that check all optional config and install it if the dependencies are now met. This means we don't know when optional config might be installed and this causes issues with hooks like `hook_install()` that try to make changes to existing config; we can't be sure the config it wants to change exists and if it doesn't now (but will later) the change in the hook either fails or is never applied.

With Drupal 10, this is causing the issue described above: https://github.com/localgovdrupal/localgov_core/issues/158#issuecomment-1377514831

**Comment by finnlewis** [comment]
> Adding non-existent permissions to a role is not allowed. The incorrect permissions are "use text format wysiwyg".
> 
> Caused by
> 
> https://github.com/localgovdrupal/localgov_core/blob/f857b3e566e4687087bffd7e277fc4a594cefb04/modules/localgov_media/localgov_media.module#L17
> 
> I think this is because the relevant config is in optional and so not guaranteed to be installed.

Could we not check for the existance of the permission before calling $role_object->grantPermission ?

**Comment by stephen-cox** [comment]
> Could we not check for the existence of the permission before calling `$role_object->grantPermission` ?

We can check that the text format exists, but as this code is run when the `localgov_media` module is installing, and it's not actually installing anything at this point (or certainly not the text format), so the check will fail and the grant permission code will never run. What we need is an event or hook that runs after module config is installed.

**Comment by stephen-cox** [comment]
Closing as we have D10 support working
