### ISSUE TITLE
CKEditor 5 and Linkit

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_core#160]
From Slack: 

> "Afternoon all. Anyone had any issues with LinkIt not working properly with CKE5? I've noticed the 'Drupal link' setting doesn't seem to appear when switching WYSIWYG from CKE4 to 5, to enable LinkIt under the CKEditor plugin settings on Admin>>Config>>Content authoring>>Text formats and editors>>WYSIWIG"

See 
 - https://www.drupal.org/project/linkit/issues/3232190#comment-14859457
 - https://www.drupal.org/files/issues/2022-12-14/3232190-113.patch

I'm going to test the patch.

**Comment by keelanfh** [comment]
I've been playing around with this for a bit and it seems to work reasonably well.

The toolbar for CKEditor 5 does push some of the icons off to the right in some layouts, especially tabbed layouts.

Do we need a separate issue for CKEditor 5 generally? It would be great to get it implemented - it would make it a lot easier to create and edit tables, for example.

**Comment by stephen-cox** [comment]
CKEditor 5 will become the editor in Drupal 10, so any issues with it will need ironing out before there can be stable LGD release with D10 support. I'm working towards an alpha release #158, but it's still a way off.

Please create issues for any problems you find. They will certainly be looked at as part of the D10 work.

**Comment by keelanfh** [comment]
OK, that's helpful to know. I'm considering an upgrade to CKEditor 5 before a D10 upgrade.

**Comment by justinepocock** [comment]
Linkit is meant to be working with D9.5.7 onwards and ckeditor5  - with the patch above having been rolled in - however I'm having issues getting it to work.

**Comment by keelanfh** [comment]
This seems to be fine after upstream changes, so closing.
