### ISSUE TITLE
The Lede should be configurable

### ISSUE THREAD

**Issue by rgcarr** [localgovdrupal/localgov_core#164]
The function getLede() isn't currently configurable but renders a node summary or a set phrase 'All pages relating to [[term name in lower case]]' for taxonomy terms. It is part of /localgov_core/src/Plugin/Block/PageHeaderBlock.php

```
protected function getLede() {

    // Return node summary if it exists.
    if ($this->entity instanceof Node && $this->entity->hasField('body')) {
      return [
        '#type' => 'html_tag',
        '#tag' => 'p',
        '#value' => $this->entity->get('body')->summary,
      ];
    }

    // Return a term string.
    if ($this->entity instanceof Term) {
      return [
        '#type' => 'html_tag',
        '#tag' => 'p',
        '#value' => $this->t('All pages relating to @label.', ['@label' => strtolower($this->entity->label())]),
      ];
    }

    return NULL;
  }
```
The content generated by this function is not themeable, so it would be good to provide some sitewide configuration options, for example, generating a lede from a different node field, or customising/hiding the lede for a taxonomy term.

**Comment by stephen-cox** [comment]
The page header block is templated, so you should be able override the lede in a theme preprocess function and add your own logic.

Very crudely, the following will change the lede on _all_ pages:

```php
function THEME_preprocess_block(&$vars) {
  if ($vars['plugin_id'] == 'localgov_page_header_block') {
    $vars['content'][0]['#lede']['#value'] = 'My lede';
  }
}
```

Will this do what you need?

**Comment by rgcarr** [comment]
Thanks, I'd implemented a theme hook after I'd raised the question on Slack, and Andy Broomfield came back with a suggestion. I added the following to hide the Taxonomy lede, which is where my problem originated from.

```
function THEME_preprocess_localgov_page_header_block(&$variables) {
  // lede is an array set by default with 
  //   #type => "html_tag"
  //   #tag => "p"
  //   #value => t(String) - summary for nodes; text + Term title for taxonomy
  
  // Set 'lede' value to empty if on a Taxonomy term page
  if (\Drupal::routeMatch()->getRouteName() == 'entity.taxonomy_term.canonical') {
    $variables['lede'] = [];
  }
}

```
Knowing that this content is templated is a massive help (thanks), but I think some config options for the lede might more useful for a broader audience in the longer term... but appreciate this probably isn't a huge priority.

Happy to close this issue in the meantime. I might revisit if I have some time
