### ISSUE TITLE
Image label marked visually-hidden

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_core#165]
`    label: visually_hidden
`

The field label is set to visually hidden, which means screen readers read out "Image" on every image, which is unnecessary. 
We can set this to Hidden

**Comment by msayoung** [comment]
Reported by @RyanFH257

**Comment by msayoung** [comment]
@bisd - i think you've been working on something similar - would you like this one too?

**Comment by keelanfh** [comment]
Same as https://github.com/localgovdrupal/localgov/issues/504

Essex's fix for this was https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/65

**Comment by bisd** [comment]
Thanks @keelanfh and @msayoung - I was thinking of changing the attribute in the 'label_display' setting of the "themes/contrib/localgov_base/templates/field/field.html.twig" template from "visually-hidden" to "invisible" 

![image](https://user-images.githubusercontent.com/2633608/226344458-14c86b7a-b709-46a1-a8a0-e6d25f014d0e.png)

But happy to look into the way it was done by Essex here:
https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/65

**Comment by msayoung** [comment]
Hi @bisd - better to change it in the field config, rather than in the template in my opinion. :)

**Comment by markconroy** [comment]
I agree with @msayoung 

If we edit that `field.html.twig` template, then it will affect _all_ fields, but there are cases where we _do_ want the label to be visibly-hidden, so much better to do it on a field-by-field basis in the config.
