### ISSUE TITLE
PageHeaderBlock.php does not render lede in node preview

### ISSUE THREAD

**Issue by ctorgalson** [localgovdrupal/localgov_core#168]
When previewing a node via the "Preview" button in the node edit form, the "lede" (summary content shown below the node title) is always empty.

This is because [the relevant code](https://github.com/localgovdrupal/localgov_core/blob/2.x/src/Plugin/Block/PageHeaderBlock.php#L122-L127) only considers route parameter option types whose names begin with `entity:`. During a node preview, no parameter option has that name, but there is an option type named `node_preview` that can be used.

Pull request coming today or Monday.

**Comment by justinepocock** [comment]
I can see in the code that @ctorgalson has done this. So I'm going to close this issue.
