### ISSUE TITLE
Generator meta tag self promotion.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_core#176]
I ran into this earlier: https://www.viko.co.uk/blog/local-government-cms/

It's an analysis of which CMS platforms UK local government uses. Drupal's doing pretty well, but it made me think - which of those sites are LocalGov and which are regular Drupal?

One of the methods that analysis uses to figure out what powers a site is to check the Generator meta tag. So how about we alter it to say "LocalGov Drupal" instead of just "Drupal"?

**Comment by rupertj** [comment]
I've had a stab at it. With that commit added the result is:
`<meta name="Generator" content="LocalGov Drupal (https://localgovdrupal.org)"/>`

**Comment by MariosORION** [comment]
I like the idea, makes sense to add the flavour of Drupal that the site is built on.

**Comment by budda** [comment]
Great, simple, idea! +1
