### ISSUE TITLE
Version numbering gap

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_core#197]
This is just a quick check, but I notice the version number jumps from [2.1.10](https://github.com/localgovdrupal/localgov_core/releases/tag/2.1.10) to [2.11.1](https://github.com/localgovdrupal/localgov_core/releases/tag/2.1.11) (which is tagged as 2.1.11).

So I'm guessing this was accidental, though given the jump that then happens in [2.11.2](https://github.com/localgovdrupal/localgov_core/releases/tag/2.11.2) which is tagged with the high number, theres no point going back and trying to renumber correctly.

Do we need to document this anywhere or just accept that as long as its a bigger number it's fine.

**Comment by stephen-cox** [comment]
Whoops - looks like I put the point in the wrong place when making a release :roll_eyes: 

It shouldn't break stuff though as the numbers are increasing.
