### ISSUE TITLE
Move 'compare' tab on revisions from bottom to top of page

### ISSUE THREAD

**Issue by ElizabethPace** [localgovdrupal/localgov_core#224]
Often when comparing revisions on content pages, it's newer revisions a user wants to compare. The compare button is at the bottom of the page and a lot of scrolling's involved if it's a page with a lot of revisions.

Consider moving the compare button to the top of the page to make the comparing revisions easier.

**Comment by finnlewis** [comment]
Hi @ElizabethPace, 

Thanks for the suggestion and sorry not to reply sooner.

I've just taken a quick look and I think the 'Compare selected revisions' button is provided by the diff module, which is not actually enabled on a default install. This is the module http://drupal.org/project/diff 

So I've just enabled it and the revisions tab now looks like this: 

![image](https://github.com/localgovdrupal/localgov/assets/326588/b990bacb-430d-4da1-86f9-518d9963d0ac)

To move this button we would probably need to hook into that form with a hook_form_alter function to re-order the form elements. Maybe we could look at improving the diff module to provide an option to present the button at the top or at the bottom. 

It would be good to find out if this is a common need with other users. 

@willguv has this come up in the content or product meetings at all?

**Comment by willguv** [comment]
Hi Finn, not this button specifically but there's been mentions of the save button being way down the page on occasion, with lots of scrolling

Could talk about having top right and bottom left positions for important buttons like this one. Can help to define

We've also talked in Essex about sticking the button panel in position as the page scrolls. Not resolved yet - shall I come to next meet and chat about it?

**Comment by willguv** [comment]
Thanks @ElizabethPace for posting on GitHub. If you @willguv I'll pick it up too

**Comment by markconroy** [comment]
Rather than moving the button to the top of the page, how about we duplicate the button and have it at the top _and_ the bottom of the page?

Like so:
![Screenshot 2024-05-30 at 14 36 22](https://github.com/localgovdrupal/localgov/assets/2183332/2728af18-96dd-46dc-89e0-95da8b178d32)

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by willguv** [comment]
Excessive scrolling to buttons have come up in Essex before. Can we make them sticky at the top of the page?

**Comment by markconroy** [comment]
@willguv it looks like the Diff module now has a compare button on top and bottom of page, so we don't need to implement it any more.

I've updated my PR so the top button is sticky when you scroll the page. 

1. Compare button at top of page

![Screenshot 2024-07-03 at 10 45 41](https://github.com/localgovdrupal/localgov_core/assets/2183332/3c87c9a4-04c0-4b3a-9624-9d5012a9e49d)


2. Compare button sticky at top of page when you scroll

![Screenshot 2024-07-03 at 10 45 30](https://github.com/localgovdrupal/localgov_core/assets/2183332/ccf5f9d6-bc06-4942-a40e-4ebec4ca5321)
