### ISSUE TITLE
Installing permissions for authors and content editors

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_core#30]
The localgov_roles module installs permissions for the 4 service content types. It doesn't do anything for other content types as we don't know which other content types will be enabled at install time. We need some way of installing these so athours and editors can use the workflow defined in localgov_workflow.

**Comment by Adnan-cds** [comment]
I came across this very issue while setting up the LocalGov Croydon site :(

FAO @finnlewis @stephen-cox @willguv @andybroomfield

**Comment by willguv** [comment]
I expect this will come up in next week's retro - there was extra dev work we needed to do to bridge the gap between LGD and having a production ready site

Could optional modules have bundled workflow, or look for workflow in services (if services is installed)?

**Comment by ekes** [comment]
## Background

Related: 
 * https://github.com/localgovdrupal/localgov_directories/issues/95
 * https://github.com/localgovdrupal/localgov_directories/issues/15

Also for information:
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/node/node.install#L125
```
  // IMPORTANT: Modules SHOULD NOT automatically grant any user role access
  // permissions in hook_install().
```
although `node` moudle then goes to for the `access content` to anon and authenticated. As does media in media.install. And we then do the same for view permissions in https://github.com/localgovdrupal/localgov_geo/blob/3d5a905ff3ac634401daaa9940ddcd5d031df76c/localgov_geo.install#L14 Again for anon and authenticated.

But the problem then arose that when the site in #95 was configured permission to create Venue content was granted, but permission to create the Geo entity wasn't.

Except for services, as mentioned no other content: guides, step-by-step, directory add permissions for this role.
So the desire is really about the role provided by this module:

https://github.com/localgovdrupal/localgov_directories/issues/95#issuecomment-853002690
> content designers need to be able to create, edit and publish all types of directories content.
> Croydon has these permission now and use them all the time. While I was there, Brighton content designers created everything they could too. (Creating facets wasn't available until you built them, but was always part of the plan).

## Proposal

So it feels like this module (localgov_role) should be assigning the permissions to its role. It of course doesn't know about which permissions are being added. But by maintaining most of the logic in this module it saves repeating it in every single localgov module that wants, and it might make it clearer.

With that in mind. I'm thinking declaring a 'hook' or config in this localgov_role module that it checks when a new module gets installed. The new module then just needs to declare a list of which permissions it should given to the content editor should this module be installed and checking for the list. The list could already define which localgov_roles assuming there might be more?

Thoughts?

**Comment by ekes** [comment]
Gone with

HOOK_localgov_roles_default(). As this can be called directly per module when another module is installed (from hook_modules_installed), and can be called with invokeAll from hook_install when the roles module itself is installed. The former will add the permissions for the newly installed modules; the latter will install the permissions for all modules.

The format template for the hook will be:

```
HOOK_localgov_roles_default() {
  return [
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper\RolesHelper::EDITOR_ROLE => [
      'example create permission',
      'example edit permission',
      'example admin permission',
    ],
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper\RolesHelper::AUTHOR_ROLE => [
      'example create permission',
      'example edit permission',
    ],
  ];
}
```
