### ISSUE TITLE
Question about new release

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_core#50]
Hi Finn,
I have realized there's some unreleased code in the master branch that carries the responsive_banner Media image display mode and related configs.  I have just created a **release** branch from the master branch.  Because there's no difference between the release branch and the master branch, there is nothing to raise a pull request against!  Is it okay if I just tag the release branch as **1.0.0-alpha2**?

**Comment by finnlewis** [comment]
sure thing!

**Comment by Adnan-cds** [comment]
Done.  Thanks :)
