### ISSUE TITLE
Add view mode for 'Card'

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_core#57]
Lots of websites use a "Card" view mode. Our current profile only allows teaser as a view mode, which is fine for some listings like a search result or service listing, but often we might like a slightly different layout, such as a featured news like what is on the Brighton-Hove homepage.

![Screenshot 2021-04-09 at 15 11 57](https://user-images.githubusercontent.com/2183332/114193412-653a1d80-9946-11eb-80c0-0f8b8f014f38.jpg)

Once we have this as a view mode, I'd suggest we place a template called `node--card.html.twig` in the `localgov_skeleton` theme so all themes can use the HTML from it and not invent their own per theme/site.

**Comment by msayoung** [comment]
I think this is a great idea @markconroy

**Comment by markconroy** [comment]
@msayoung assigning you and me to this. Let's see how gets to it first.
