### ISSUE TITLE
Field renaming is wiping out Paragraphs

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_core#75]
Hello,
We have run the [field renaming update](https://github.com/localgovdrupal/localgov_theme/releases/1.0.0-alpha4) yesterday.  Fields were renamed correctly without any issues.  Unfortunately, some Paragraph entities referenced by the field_topics field (now localgov_topics) became orphaned in the process.  These were later purged by the [Entity reference revisions module](https://git.drupalcode.org/project/entity_reference_revisions/-/blob/8.x-1.x/entity_reference_revisions.module#L310).  Because it uses a [queue worker](https://git.drupalcode.org/project/entity_reference_revisions/-/blob/8.x-1.x/src/Plugin/QueueWorker/OrphanPurger.php), it wasn't until this morning that the wiping was executed.  This left me puzzled as to the cause given that all looked fine immediately after deployment.  Eventually I had to restore some lost rows of the relevant tables from an older database backup to bring back normalcy.

The effected Paragraph was [topic_list_builder](https://github.com/localgovdrupal/localgov_services/blob/2.x/modules/localgov_services_sublanding/config/install/paragraphs.paragraphs_type.topic_list_builder.yml) bundled with the localgov_service_sublanding page submodule.  But it can happen to any Paragraph referenced from a renamed Entity reference revision field.

I don't see any quick solution other than not to [rename field_topics](https://github.com/localgovdrupal/localgov_services/blob/6ee3adc340647f647f56ee445bfae5e1d57018fa/modules/localgov_services_sublanding/localgov_services_sublanding.install#L23).

@andybroomfield @finnlewis @tom-steel

**Comment by andybroomfield** [comment]
Since this is already released, I don't think we can revert.
Should we look at using a migration to move them over?

**Comment by andybroomfield** [comment]
@Adnan-cds I'd like to investigate further before we pull this rename, as its essential to rename this field so it can be used at BHCC, and I think new sites will have built with the new names.

**Comment by Adnan-cds** [comment]
Hi Andy, Field renaming is fine.  We just need to skip using it on Paragraph fields.

**Comment by andybroomfield** [comment]
Except we need to rename the paragraph fields, as field_topics already exists in the BHCC site so we won't be able to install localgov_services.

**Comment by Adnan-cds** [comment]
As far as I understand at the moment, the parent_id, parent_type, and parent_field_name fields in the paragraphs_item_field_data and paragraphs_item_revision_field_data tables are the key.  Once these values get nullified, the previously mentioned Entity reference revision purger starts its job.

**Comment by andybroomfield** [comment]
ok, so first idea is can we acomplish this with a migration? Create the new field, use migrate to clone data, then remove the old field.

**Comment by Adnan-cds** [comment]
> then remove the old field.

As far as I understand, as soon as you will remove a Paragraph field (i.e. an Entity reference revision field), the Paragraph entities referenced by it will loose their parent data.  But if you migrate both the Paragraph field and the Paragraph entities it references, then migration may work.

**Comment by andybroomfield** [comment]
Other sites (London councils @danchamp and Lambeth @finnlewis, @stephen-cox, @ekes) experincing this issue?

**Comment by andybroomfield** [comment]
Ok, I verified this issue by
- doing a fresh install on the pre renamed fields
- installing the old version of localgov_demo,
- upgrading to latest 1.x modules
- run drush updb -y
- run drush cron

Renamed topics was there before running cron, but was cleared of values once cron was run.

**Comment by andybroomfield** [comment]
@Adnan-cds the other option is if it is a paragraph field to do a DB search and replace?

**Comment by Adnan-cds** [comment]
> but was cleared of values once cron was run.

That's right.  The Queue workers are applied during cron runs.  Depending on how many items are in the queue, this can take a while to get to.  Almost like a timebomb!

> the other option is if it is a paragraph field to do a DB search and replace?

That may work.  But I haven't tried it, so can't say for sure.  What I understand is, these Paragraph fields need different treatment than other fields.

**Comment by danchamp** [comment]
> Other sites (London councils @danchamp and Lambeth @finnlewis, @stephen-cox, @ekes) experincing this issue?

@andybroomfield Sorry, we had no Paragraph entities to migrate so didn't experience this issue.

**Comment by andybroomfield** [comment]
I did a quick experiment by doing a database sql query. The following works and keeps the topic fields intact after cron runs.
````sql
UPDATE `paragraphs_item_field_data` SET `parent_field_name` = 'localgov_topics' WHERE `parent_field_name` = 'field_topics';
UPDATE `paragraphs_item_revision_field_data` SET `parent_field_name` = 'localgov_topics' WHERE `parent_field_name` = 'field_topics';
````
If we can add this query into the field rename helper if it is working with a paragraphs field, think page components will be the other one, but the old version of localgov_demo doesn't have any of those, I think this should resolve the bug.

FAO @Adnan-cds.

**Comment by willguv** [comment]
Sorry you experienced this @Adnan-cds @tom-steel - it was a surprise to hear this happened. Well done for tracking down the issue.

Shall we have a short retro?
- to share understanding of the issue
- to pick up any learnings for future changes of this type (eg switch to D9, refactoring of front end theme)

What's your view @finnlewis? Thanks all

**Comment by richardaclarke** [comment]
I'd be happy to join a retro, @willguv. The tricky thing with this one was that it wasn't evident straightaway, it basically waited until everyone was asleep. So maybe a longer period of testing is needed, or we need to have more awareness of Cron tasks that run later.

**Comment by andybroomfield** [comment]
Lets try to get a fix in then happy to join a retro.

**Comment by Adnan-cds** [comment]
> If we can add this query into the field rename helper if it is working with a paragraphs field,

If this works then yes, it can be added to [localgov_services_sublanding_update_8001()](https://github.com/localgovdrupal/localgov_services/blob/6ee3adc340647f647f56ee445bfae5e1d57018fa/modules/localgov_services_sublanding/localgov_services_sublanding.install#L20)

> think page components will be the other one,

Page component renaming worked okay as it is an Entity reference field instead of an Entity reference revision field.

> Sorry you experienced this - it was a surprise to hear this happened.

No need to be sorry Will. I tested the thing thoroughly before deploying.  We couldn't spot the problem early as it didn't occur immediately after deployment.  We deployed on Tuesday evening and the Paragraphs were removed early morning on Wednesday (i.e. yesterday).  Thankfully, the database backup taken around 0100 on Wednesday had all the Paragraphs, so it took a few hours to restore them.  Apart from that, the rest of the field renaming worked fine.  The Croydon Drupal site is now enjoying the renamed fields.  No further complains from any site user so far :)

**Comment by finnlewis** [comment]
Happy to run a retro / review but probably best to allow Andy to work on his fix first. 

It sounds like @Adnan-cds has resolved the immediate issue at Croydon, which is good to know. Is that right @Adnan-cds @richardaclarke ?

We also noted in our standup that this should be highlighted to anyone else who might be affected. Westminter, Lambeth, Bracknell .

I'll post in the product and technical channels, but @willguv perhaps you can also email contacts and councils who are live.

**Comment by Adnan-cds** [comment]
> resolved the immediate issue at Croydon, which is good to know. Is that right @Adnan-cds

That's right.  No complains from site users so far.
