### ISSUE TITLE
Field rename fails if there is existing config with updated field name already present

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_core#78]
`[error]  Attempt to save a configuration entity 'node.localgov_related_links' with UUID 'c40b2e2a-1440-4543-90d1-951e95390a14' when this UUID is already used for 'node.field_related_links'`

This happens if the config from a previously updated site on the same host is present in config sync.
I ran into it whilst rolling back the field renames to check the update works and had a config export from the newer version in the sync directory.

Making a note of it, this may be released to the `drush deploy` fix as that tries to preserve the UUID of config entities if they exist for the new field names.
The practical effect should be minor, just rename the sync directory temporary to run the update. Most sites will either not have the config in the sync directory when they do the update, or will have it deployed through git or drush deploy so the rename should work fine.

FAO @Adnan-cds in case this has any effect / comment.

**Comment by Adnan-cds** [comment]
Hi Andy,
If I export the config after running the field renaming updates, the config files for the older fields get deleted.  That should prevent the occurrence of this issue.  Is that not happening then?

**Comment by andybroomfield** [comment]
@Adnan-cds What I mean is that (from previous testing) my config sync directory had files for `field.field_node.localgov_related_links` left over.

**Comment by Adnan-cds** [comment]
If this only happens during testing then I won't worry too much.  But if you feel that it can happen to production sites then yes, we need to do something about this.
