### ISSUE TITLE
Add <br> to the CKEditor allowed HTML tags

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_core#86]
Without `<br>` content editors cannot use soft returns, limiting the options for vertical spacing of inline content.

**Comment by ekes** [comment]
#53 fixed with #54 

Did this not filter through to the versions in use yet, or is it lost somewhere?

**Comment by danchamp** [comment]
Thanks @ekes, my bad, should have checked a fresh install.

**Comment by danchamp** [comment]
@ekes Scratch that, I can't see changes to `allowed_html` in #54:

https://github.com/localgovdrupal/localgov_core/pull/54/files

**Comment by danchamp** [comment]
Flip-flop. TIL what filter_autop is.

**Comment by ekes** [comment]
It was `filter_autop` which converts /n or /n/r to `<br/>` as far as I understand. It's tied to the wysiwyg. Is there another way of adding <br> that's needed, like a button or so?

**Comment by ekes** [comment]
Ah crossed each other :-)
