### ISSUE TITLE
Create a default Services menu in the Core install, and place in the secondary menu region

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_core#90]

**Comment by msayoung** [comment]
@markconroy @willguv any other detail to add to this?

**Comment by markconroy** [comment]
I don't think there's any more detail needed. It's just to create a menu and place it. There will be no content in the menu; it's just config.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_services/pull/125

**Comment by stephen-cox** [comment]
Done - sprint 6
