### ISSUE TITLE
Workflows : preview draft content exactly as it will appear

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_core#94]
## User story

**As a** content author

**I want** to preview the draft content exactly how it will appear

**So that** I can see how my content looks and feels and reads before sending for review.

## Notes: 

Drupal preview is historically rubbish. Is this still the case? If so, do we need another solution?

https://www.drupal.org/project/preview_link ?

**Comment by stephen-cox** [comment]
@willguv @msayoung I'm looking at content preview, but I haven't been involved in the discussions on this and the specification on this ticket is a bit sparse.

The [Preview Link](https://www.drupal.org/project/preview_link) module allows content editors to generate a link that can be passed around to check how a draft page looks without needing to login. This could be useful in allowing others to view the page or send yourself a link to check on a mobile phone, but it doesn't really help a great deal if the motivation for this is to allow the content editor to check the page before saving it.

I have enabled Preview Link on the test site. This is the sort of URL it generates: https://test.localgovdrupal.org/preview-link/node/74/9b8da2e4-556e-44b3-96f0-3136e28fe3e9

If the motivation for this is for content editors to see what their changes look like at a range of page sizes without leaving the edit page then the [Responsive Preview](https://www.drupal.org/project/responsive_preview) module looks to be a better option. This adds the option to view the page at a range of mobile widths in a modal pop-up.

I have also enabled Responsive Preview on the test site. When viewing or editing a page there's now a mobile phone icon in the toolbar on the far right. Clicking this allows you to select a range of mobile devices and brings up the page in an overlay.

Do either of these options allow the sort of content preview desired?

**Comment by willguv** [comment]
Hi @stephen-cox it feels like the solutions above work for two kinds of users, and we could potentially include both in LGD

- I wasn't involved in the Preview link discussions, but the need is to provide content editors with a way of getting approval for a page from a third party who does not have a log in to the site

- Responsive Preview sounds like a useful tool for editors to check their work on different devices. We haven't had this to date, so it's worth us circulating to potential users to see what they think

I'll have a play with both - thanks for doing this work

**Comment by msayoung** [comment]
Oh, I had thought this was actually just about making sure that authors can Preview before they save. 
@finnlewis can you clarify ?

**Comment by finnlewis** [comment]
I will clarify!

**Comment by stephen-cox** [comment]
The content workflow WG decided that both these modules are useful.

**Comment by finnlewis** [comment]
@stephen-cox ready to merge, then we can start separating localgov_workflows out on https://github.com/localgovdrupal/localgov_core/issues/111
