### ISSUE TITLE
Workflow: approval dashboard

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_core#95]
## User story 

**As an** editor,
**I want to:** view a list of content sent for approval,
**So that** I can review/approve/reject as necessary

## Notes

An approvals dashboard is a view in Drupal that can be accessed by editors. 
Suggest this is a tab available from the Content Overview screen.

It must show a list of content that has been sent for approval and yet to be approved/published.

By default, it should be sorted to show content that was sent for approval first (last updated?) . There should also be an option to sort showing content that was most recently sent for approval.

## Acceptance tests:

1. Log in as and editor
2. Navigate to the moderated queue
3. Columns include:
·       Title (clickable to page front end/preview)
·       Content type
·       Author
·       Sent for approval date and time
·       Status – this should always be ‘sent for approval’
·       Approve/reject/edit (clickable to page back end/edit screen)
4. When an editor approves or rejects a page edit, the content should no longer appear in the dashboard.
5. Log in as author
6. See the moderation queue
7. Not be able to do anything 

## Wireframe: 

https://design.penpot.app/#/view/e136cb40-d014-11eb-97a9-7472ffaca84b/e136cb41-d014-11eb-97a9-7472ffaca84b?token=mKLdKAWLPeTj3zF8Bk-A0A&index=0 

## Suggested tasks:

- [x] Take a quick look at https://www.drupal.org/project/workbench to see
- [x] Demo https://www.drupal.org/project/workbench to the working group if it seems like a goer. 
- [x] Build out changes either on top of workbench or with core views

**Comment by msayoung** [comment]
@willguv @lbcwebmaster @benhillsjones (is David on here?) I've written up the approvals dashboard - how does that look? 

Question - is the Last updated column good enough to see when content was sent for approval?

**Comment by andybroomfield** [comment]
Theres the review queue that is part of the BHCC site (never ported to Localgov).
Also Drupal has a built in Moderated content view which could be altered.

<img width="1292" alt="Screenshot 2021-06-21 at 1 31 16 pm" src="https://user-images.githubusercontent.com/1467480/122762492-4684cb00-d295-11eb-84f7-433bd6d3ac76.png">

**Comment by stephen-cox** [comment]
I have enabled the Workbench module on the testing site so the content workflow working group can take a look tomorrow. I've also enabled the existing LocalGov Workflows module that provides a simple set of content states and transitions between them.

I will come to the working group meeting tomorrow if I can, although there's a reasonable chance I won't be able to make it.

Workbench comes with its own menu and a configurable content overview page: https://test.localgovdrupal.org/admin/workbench. We could add our own views of content in need of moderation to this overview page if we wanted.

**Comment by stephen-cox** [comment]
Having discussed this with the Content Workflow Working Group the decision has been made to go with the core Moderated Content views for now. These can be reviewed once people start using them Workbench added later if a more customisable editor dashboard is required.

**Comment by stephen-cox** [comment]
@willguv @msayoung This work has been deployed to the test site: https://test.localgovdrupal.org/

You can checkout the approvals dashboard here: https://test.localgovdrupal.org/admin/content/localgov_approvals

**Comment by msayoung** [comment]
Great, thanks @stephen-cox 
pinging @OliverHannan @tom-steel @davidsiddal too.
Login details for the test site in our Slack channel

**Comment by finnlewis** [comment]
@stephen-cox ready to merge I believe!
